name : Build & Release WPF App

on:
  push:
    tags:
      - 'v*'    #Declencher lorsque l'ont tag une version commençant par v
    
jobs:
  build-and-release:            #le nom du groupe de taches
    runs-on: windows-latest     #L'environnement des taches
    permissions:
      contents: write
    steps:
      - name: 1. Récuperer les sources
        uses: actions/checkout@v4

      - name: 2. Installer .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: 3. Restaurer les dépendances
        run: dotnet restore                   # Cette commande trouve automatiquement le .slnx à la racine

      - name: 4. Exécuter les tests unitaires    # On exécute les test unitaire
        run: dotnet test --no-restore --verbosity normal

      - name: 5. Préparer le numéro de version
        id: prep_version  # On donne un ID pour pouvoir le cibler plus tard
        shell: bash
        run: echo "CLEAN_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: 6. Publier l'application WPF
        # Ici, on appelle le résultat de l'étape "prep_version"
        run: >
          dotnet publish ArchipelagoParser/ArchipelagoParser.csproj 
          -c Release 
          -r win-x64 
          --self-contained true 
          -p:PublishSingleFile=true 
          -p:Version=${{ steps.prep_version.outputs.CLEAN_VERSION }}
          -p:FileVersion=${{ steps.prep_version.outputs.CLEAN_VERSION }}
          -p:AssemblyVersion=${{ steps.prep_version.outputs.CLEAN_VERSION }}
          -o ./publish

      - name: 7. Compresser le fichier de sortie
        run: Compress-Archive -Path ./publish/* -DestinationPath ArchipelagoParser-${{ github.ref_name }}.zip

      - name: 8. Créer la Release sur GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: ArchipelagoParser-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 9. Notification Discord
        uses: sarisia/actions-status-discord@v1
        # S'exécute même si une étape précédente a échoué
        if: always()                          
        with:
            webhook: ${{ secrets.DISCORD_WEBHOOK }}
            status: ${{ job.status }}
            title: "Build SpoilerArchipelagoParser : ${{ github.ref_name }}"
            # On utilise une condition ternaire pour le message
            description: |
              ${{ job.status == 'success' 
                  && format('✅ **Succès !** La version est prête. [Accéder à la Release](https://github.com/{0}/releases/tag/{1})', github.repository, github.ref_name) 
                  || '❌ **Échec !** La compilation ou les tests ont échoué. Vérifie les logs sur GitHub.' 
              }}
            color: ${{ job.status == 'success' && '0x00ff00' || '0xff0000' }}
